Repository laminas/laminas-diactoros, pull requests merged in 2021-09, with the labels that each got.

#70 PHP 8.1 support
  .laminas-ci.json
  composer.json
  composer.lock
Labels: Enhancement

#69 Update PHPDoc: allow StreamInterface in $streamOrFile in UploadedFile
  src/UploadedFile.php
Labels: Documentation, Enhancement

#73 fix build status badge url
  README.md
Labels: Documentation

#72 Support for web servers that send HTTP2 request protocol as HTTP/2.0. Fixes #71
  psalm-baseline.xml
  src/MessageTrait.php
  test/MessageTraitTest.php
Labels: Enhancement

#68 Update readme to point to updated contribution guideline pages
  README.md
Labels: Documentation

#75 [QA] Using php >= 7.3 syntaxes
  src/AbstractSerializer.php
  src/Response.php
  src/Response/JsonResponse.php
  src/Response/Serializer.php
  src/UploadedFile.php
  src/Uri.php
Labels: Enhancement
