Repository laminas/laminas-diactoros, pull requests merged in 2022-07, with the labels that each got.

#98 Fixed `UploadedFile::moveTo()` so it actually removes the original file when used in CLI context, and doesn't leave orphaned files
  psalm-baseline.xml
  src/UploadedFile.php
  test/UploadedFileTest.php
Labels: Bug, Enhancement

#106 Refined types as per `laminas/laminas-coding-standard:2.3.x` upgrades
  composer.json
  psalm-baseline.xml
  src/Exception/InvalidStreamPointerPositionException.php
  src/Exception/UploadedFileAlreadyMovedException.php
  src/MessageTrait.php
  src/Request/ArraySerializer.php
  src/Response/ArraySerializer.php
  src/functions/create_uploaded_file.legacy.php
  src/functions/marshal_uri_from_sapi.legacy.php
  src/functions/parse_cookie_header.legacy.php
  src/functions/parse_cookie_header.php
  test/CallbackStreamTest.php
  test/HeaderSecurityTest.php
  test/Integration/RequestTest.php
  test/Integration/ResponseTest.php
  test/Integration/ServerRequestFactoryTest.php
  test/Integration/ServerRequestTest.php
  test/Integration/StreamTest.php
  test/Integration/UploadedFileTest.php
  test/Integration/UriTest.php
  test/MessageTraitTest.php
  test/PhpInputStreamTest.php
  test/Request/SerializerTest.php
  test/RequestTest.php
  test/Response/ArraySerializerTest.php
  test/Response/HtmlResponseTest.php
  test/Response/JsonResponseTest.php
  test/Response/RedirectResponseTest.php
  test/Response/SerializerTest.php
  test/Response/TextResponseTest.php
  test/Response/XmlResponseTest.php
  test/ResponseTest.php
  test/ServerRequestFactoryTest.php
  test/ServerRequestTest.php
  test/StreamTest.php
  test/UriTest.php
  test/functions/MarshalUriFromSapiTest.php
Labels: Enhancement

#109 Add `export-ignore` attribute for `/renovate.json`
  .gitattributes
Labels: Enhancement

#110 Remove duplicate `config.allow-plugins` key in composer.json
  composer.json
Labels: Enhancement

#113 Fix static return type in RequestTrait
  psalm-baseline.xml
  src/RequestTrait.php
  test/StaticAnalysis/RequestInterfaceStaticReturnTypes.php
Labels: Documentation, Enhancement
