Repository laminas/laminas-diactoros, pull requests merged in 2023-05, with the labels that each got.

#146 Drop legacy helper functions in Zend namespace
  composer.json
  composer.lock
  psalm-baseline.xml
  src/functions/create_uploaded_file.legacy.php
  src/functions/marshal_headers_from_sapi.legacy.php
  src/functions/marshal_method_from_sapi.legacy.php
  src/functions/marshal_protocol_version_from_sapi.legacy.php
  src/functions/marshal_uri_from_sapi.legacy.php
  src/functions/normalize_server.legacy.php
  src/functions/normalize_uploaded_files.legacy.php
  src/functions/parse_cookie_header.legacy.php
Labels: BC Break, Feature Removal

#152 Remove marshalUriFromSapi function
  composer.json
  docs/book/v3/api.md
  docs/book/v3/migration.md
  psalm-baseline.xml
  psalm.xml.dist
  src/functions/marshal_uri_from_sapi.php
  test/ServerRequestFactoryTest.php
  test/UriFactoryTest.php
  test/functions/MarshalUriFromSapiTest.php
Labels: BC Break, Documentation, Enhancement

#154 Remove PhpInputStream
  docs/book/v3/migration.md
  psalm-baseline.xml
  src/PhpInputStream.php
  src/ServerRequest.php
  test/PhpInputStreamTest.php
Labels: BC Break, Documentation

#155 Ensure fromGlobals does not use superglobals when passed empty arrays
  docs/book/v3/migration.md
  psalm-baseline.xml
  src/ServerRequestFactory.php
  test/ServerRequestFactoryTest.php
Labels: Bug

#156 Document PSR-7 v2 impact
  composer.json
  composer.lock
  docs/book/v3/migration.md
Labels: Documentation

#157 Filter integer header names during SAPI discovery
  docs/book/v3/forward-migration.md
  docs/book/v3/migration.md
  docs/book/v3/security.md
  mkdocs.yml
  psalm-baseline.xml
  src/functions/marshal_headers_from_sapi.php
  test/ServerRequestFactoryTest.php
  test/functions/MarshalHeadersFromSapiTest.php
Labels: BC Break, Bug, Documentation
